### PR TITLE
Migration von ANT auf Maven und Bugfixes

### PR DESCRIPTION
**Pull request by datazuul**
* Umstrukturierung der Projekte und Migration von ANT auf Maven Build-System

* Trennung in Einzelmodule
  * Engine Alpha (FAT JAR)
  * Engine Alpha Examples
  * Engine Alpha EDU (FAT JAR)
  * Engine Alpha EDU Beispiele
* Hinzufügen von CHANGELOG.md und LICENSE
* Bugfix: Behebung Kompilierfehler: `Pair`-Klasse aus JavaFX ersetzt durch `Pair`-Klasse aus Apache Commons
* Bugfix: Behebung Fehler in Unit-Tests von `VectorTest`

### CODE REVIEW

**Review by kelunik — APPROVED** [review]

**Comment by datazuul** [comment]
thank you for approval of merge request
but I am not able to merge (no commit rights). it is up to you to ... :-)

**Comment by kelunik** [comment]
I know, still need to migrate the server to use Maven. Unfortunately, its public IPv4 connectivity broke while making an update this week.

**Comment by moritzlerch** [comment]
Any updates to this? Would like to use V4 :)

**Comment by kelunik** [comment]
@MoritzLerch Yes, I've managed to restore the IPv4 connectivity of the server, but haven't done the migration, yet. We have planned a focus week in August, so it'll happen there if not earlier. You can use V4 also without this change. :smile:

**Comment by moritzlerch** [comment]
> @MoritzLerch Yes, I've managed to restore the IPv4 connectivity of the server, but haven't done the migration, yet. We have planned a focus week in August, so it'll happen there if not earlier. You can use V4 also without this change. :smile: 

Oh, that sounds very nice :) I actually tried to compile V4 to use it along BlueJ - with no success. This is probably caused by some weird dependency Java version problem. Is there any version you have compiled successfully that works with BlueJ?

**Comment by kelunik** [comment]
Yes, there are automatic builds available at https://git.engine-alpha.org/downloads/4.x/

**Comment by kelunik** [comment]
Thank you again for the work! I've now manually applied it in https://github.com/engine-alpha/engine-alpha/commit/dffe4bdae4e0c8e87588407fce99bc09e389882b, because we made some changes before merging the PR, which of course resulted in lots of conflicts.

**Pull request closed without merging**
